### PR TITLE
Update spec file to new release 0.98 for package

### PR DESCRIPTION
**Pull request by smooge**
Make change to spec file to reflect version 0.98

### CODE REVIEW

**Comment by ericcurtin** [comment]
@smooge could we remove the shellcheck changes from this PR. We already have another PR for that:

https://github.com/containers/initoverlayfs/pull/24

**Comment by ericcurtin** [comment]
Another thing that's very important is testing shellcheck changes...

Making suggested shellcheck fixes can break things, I'm one of the guilty parties who have broken scripts from making shellcheck changes...

And we can't rely on CI to test shell changes yet, because it's not set up to execute any shell scripts or C code yet, so changes have to be tested manually...

**Comment by ericcurtin** [comment]
We can merge https://github.com/containers/initoverlayfs/pull/24 without CI the extensive CI, we just have to make sure the changes are manually tested, because none of these shell scripts are executed in CI yet...

**Comment by smooge** [comment]
I can undo the shellcheck changes and just put "# shellcheck disable=SC????,SC2016 to allow testing cleanup.

**Pull request closed without merging**
