### PR TITLE
install: detect where the initramfs exists

### PR DESCRIPTION
**Pull request by dougsland**
Helps distros which the file is not on /boot dir.

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
What about searching for /proc/cmdline? 
After first reboot? 
Ahh sorry I missed that, 
https://github.com/containers/initoverlayfs/pull/43/files#diff-e2ccc9dce797727d6ec05c10a6d179c53d46b883845be7223be33590c66e7946R68

It is still failing
The problem does also exist in storage_init
 https://pastebin.com/2MaZU0ys

**Comment by ericcurtin** [comment]
Linked PR: https://github.com/coreos/rpm-ostree/pull/4721/files

We can use this detection technique for now, but I do wonder if there are more changes, rather than detection, should we have some flag we pass to initoverlayfs-install like, so we call in the other PR like:

`initoverlayfs-install -r`

with `-r` being `--rpm-ostree-preptree` or whatever that stage is called. That's more solid than guessing.

But I'm happy to merge this now if needs be so we can keep moving forward. Just say the word!

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
@Yarboa we will get to that bugfix, this is unrelated, it doesn't make that problem worse, but it will help unblock our rpm-ostree efforts if we merge this...

**Comment by Yarboa** [comment]
> @Yarboa we will get to that bugfix, this is unrelated, it doesn't make that problem worse, but this PR will help continue our rpm-ostree efforts if we merge this...
> 
> But @dougsland might be just as happy integrating this locally for now...

Did i get it correct?, Does PR enables rpm-ostree to call inioverlayfs-install during rpm-ostree build?

**Comment by ericcurtin** [comment]
@Yarboa yeah this use case is different to a human running executing initoverlayfs-install, this is building the image on the rpm-ostree build server use case

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
