### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by firasuke**

### CODE REVIEW

**Comment by dougsland** [comment]
LGTM @ericcurtin

**Comment by rhatdan** [comment]
@firasuke Thanks
But you need to sign your commits
git commit -a --amend -s
git push --force

**Comment by firasuke** [comment]
No worries, but this was done as a quick fix on GitHub's UI, and I didn't have the repository cloned, hence the lack of signature.

**Comment by ericcurtin** [comment]
@firasuke congrats, you're our first external contributor (I think).

Once you fix DCO, it will be an insta-merge.

Just to give an update on this in general, I haven't been able to continue this for a while, got pulled into other priorities.

I should give an update on where this may go in future.

We planned for this to be useful for general initial filesystems in Automotive, but in the meantime we have had great joy with device-specific mini-initramfses. Using these two things:

https://gitlab.com/CentOS/automotive/rpms/dracut-automotive
https://gitlab.com/CentOS/automotive/rpms/util-linux-automotive

Which is not something we typically do in Fedora or CentOS Stream. But our Automotive osbuild's get very device specific, so this technique is working well for us there right now.

There's folk working on Linux as a bootloader, and they may find this interesting though, there's a multiple use-cases for this potentially when we get more time to work on this.

**Comment by firasuke** [comment]
> @firasuke congrats, you're our first external contributor (I think if memory serves me right).

Thanks for the congratulations! It's just a minor typo so it's not a big deal. I also apologize for polluting the PR history with another identical PR.

Keep up the good work!

**Pull request closed without merging**
